### ISSUE TITLE
Trying to use Crom, getting "Property 'parent_of' / 'crm:P152i_is_parent_of' is configured to not be used"

### ISSUE THREAD

**Issue by KarlPineau** [thegetty/crom#27]
Hello :)

I try to use Crom, which seems really great, with the first example proposed:

    from cromulent.model import factory, Person
    p = Person("Mother")
    p2 = Person("Son")
    p3 = Person("Daughter")
    p.parent_of = p2
    p.parent_of = p3
    print(factory.toString(p, compact=False))

But it raises the following error:

    Traceback (most recent call last):
    File "/Users/karlpineau/PycharmProjects/CIDOC-CRM/main.py", line 7, in <module>
    p.parent_of = p2
    File "/Users/karlpineau/PycharmProjects/CIDOC-CRM/venv/lib/python3.6/site-packages/cromulent/model.py", line 425, in __setattr__
    ok = self._check_prop(which, value)
    File "/Users/karlpineau/PycharmProjects/CIDOC-CRM/venv/lib/python3.6/site-packages/cromulent/model.py", line 453, in _check_prop
    raise ProfileError("Property '%s' / '%s' is configured to not be used" % (which, rdf), self)
    cromulent.model.ProfileError: Property 'parent_of' / 'crm:P152i_is_parent_of' is configured to not be used

I'm not an expert of Python (3.6 here), maybe it comes from me, but it seems weird 'parent_of' is not allowed. Any idea of the issue?

Thanks :)

**Comment by azaroth42** [comment]
Hi Karl!

Thanks for checking out crom :)  The configuration for warnings is done in /cromulent/data/crm-profile.json, which is loaded at run time. The current set of properties configured to be used are the ones that we've needed for the https://linked.art/ work. You can disable the warnings by setting:

`factory.validate_profile = False`

Which then gets around the test at https://github.com/thegetty/crom/blob/master/cromulent/model.py#L386 

The documentation should be clearer about this, and shouldn't start out with something configured not to work :)

**Comment by KarlPineau** [comment]
Hi Rob!

Thanks a lot, it works fine :)

The project, and the linked art project, seems definitely interesting. I will share feedback :)

Karl

**Comment by azaroth42** [comment]
Reopening until the documentation is done :)

**Comment by azaroth42** [comment]
Updated the documentation :)
